### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by phadej**
Also resolves: https://github.com/sol/hpack/issues/53

### CODE REVIEW

**Comment by sol** [comment]
@phadej Again, sorry for the delay on this.

Firstly, thanks for taking the time to look into this.  I understand that the current situation is not ideal and causes friction with Stackage and Nix.  But I still assume that this is temporary and will eventually resolve itself.  For that reason I'm inclined to solve this by applying #55 instead, mainly for the reason that it keeps the code simple.

For Stackage and Nix hope that disabling the tests provide a temporary solution until they are on the latest version of `aeson`.

**Comment by sol** [comment]
Regarding the travis changes, I like the idea of generating `.travis.yml`.  If we could make that work with [`zalora/tinc`](https://github.com/zalora/tinc) that could be quite useful (see https://github.com/sol/hpack/commit/1e9afffdee6cdf02c51f97937f6262c44ce436bf).

**Comment by phadej** [comment]
hvr's `multi-ghc-travis` script isn't very customisable (in fact in this PR I modified it by hand after generation). In my own projects, I use [`phadej/travis-meta-yaml`](https://github.com/phadej/travis-meta-yaml) but I don't know how usable it is for others atm.

**Comment by sol** [comment]
@phadej I'm inclined to close this one.  Is that ok with you?

**Comment by phadej** [comment]
Please close, I made a new iteration: https://github.com/sol/hpack/pull/72 :)

**Pull request closed without merging**
