### PR TITLE
Improve conditional examples in README & add support for cc-options field

### PR DESCRIPTION
**Pull request by harendra-kumar**
I got confused by the incomplete example provided in the README.

### CODE REVIEW

**Comment by harendra-kumar** [comment]
* Provide complete examples of conditionals in the README
* Add cc-options field - fixes #104

**Comment by ethercrow** [comment]
Thank you, I got confused too.

**Comment by sol** [comment]
Sorry for the delay in this guys. I'm away from any computer.  Unless somebody else takes care of it, I'll try to hit the merge button next week or so.

**Comment by sol** [comment]
Thanks a lot!

**Pull request merged**
