### PR TITLE
Product, Dependencies:  add Semigroup instances for GHC 8.4 SMP compat

### LINKED ISSUE #276: SMP failure for GHC 8.4
```
[ 4 of 40] Compiling Data.Aeson.Config.Types ( src/Data/Aeson/Config/Types.hs, dist/build/spec/spec-tmp/Data/Aeson/Config/Types.dyn_o )

src/Data/Aeson/Config/Types.hs:15:55: error:
    • No instance for (Semigroup (List a))
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Monoid (List a))
   |
15 |   deriving (Eq, Show, Functor, Foldable, Traversable, Monoid)
   |                                                       ^^^^^^
```
..and..
```
[17 of 40] Compiling Hpack.Syntax.Dependency ( src/Hpack/Syntax/Dependency.hs, dist/build/spec/spec-tmp/Hpack/Syntax/Dependency.dyn_o )

src/Hpack/Syntax/Dependency.hs:35:23: error:
    • No instance for (Semigroup Dependencies)
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Monoid Dependencies)
   |
35 | } deriving (Eq, Show, Monoid)
   |                       ^^^^^^
```

### PR DESCRIPTION
**Pull request by deepfire**
Fixes #276. Tested with GHC 8.4.

### CODE REVIEW

**Comment by deepfire** [comment]
cc @sol

**Comment by sol** [comment]
@deepfire thanks a lot for looking into this!  I agree with the analysis of @quasicomputational.  Would you be willing to adapt the code?

**Comment by deepfire** [comment]
I'll try to, sure : -)

**Comment by sol** [comment]
On `master` and amended with https://github.com/sol/hpack/commit/729423e7aff2fdd2e5b63e1808a29aa82393c6c7.

**Comment by sol** [comment]
@deepfire thanks a lot for the contribution!

**Comment by deepfire** [comment]
Sorry for not being active enough on this!

**Pull request closed without merging**
