### PR TITLE
Add support for conditionals

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by phadej** [comment]
Does this warn about e.g. `github`?

**Comment by sol** [comment]
Yes, I think the warning behavior is correct now.

**Comment by phadej** [comment]
LGTM, I ported tests from my branch: https://github.com/phadej/hpack/commit/37cc2c9edff4134fd694445792ccab6d813b6542 if you want to include them.

**Comment by sol** [comment]
@phadej Thanks for the review!  And yes, please open a PR with your two test cases.

**Pull request merged**
