### PR TITLE
Conditionals and flags

### PR DESCRIPTION
**Pull request by phadej**
Supersedes https://github.com/sol/hpack/pull/36
Implements https://github.com/sol/hpack/issues/29

### CODE REVIEW

**Comment by phadej** [comment]
Travis has a bad day today. Can someone restart job later?

**Comment by mgsloan** [comment]
+1

Perhaps we can consider different defaults?  IMHO, `FlagFields { _flagFieldManual = True, _flagFieldDefault = False, _flagFieldDescription = Nothing }` seems like a better default.  In other words, by default, you need to ask for the flag in order for it to be applied.  It goes against the grain of cabal, but it seems like the point of hpack is making the recommended / standard thing be concise.

**Comment by phadej** [comment]
@mgsloan I guess which flags *defaults* you prefer is dictated by your primary use. To make conditional dependencies `manual = False, default = True` is handy; OTOH for enabling optional features (like examples / executables) `manual = True, default = False` is better.

Alternatively one could make `manual` and `default` mandatory.

I don't have strong opinion on this though.

**Comment by soenkehahn** [comment]
I'm very much in favor of `manual = True`.

**Comment by phadej** [comment]
ping @sol and @qoelet

**Comment by phadej** [comment]
The feature still missing is handling of:
```yaml
library:
  source-dirs: src
  when:
    - condition: impl(ghc >= 7.8)
      exposed-modules:
        - Data.Aeson.Extra.SingObject
        - Data.Aeson.Extra.SymTag
```

But that would require bigger changes, so I rather do it in another PR.

**Comment by phadej** [comment]
I don't know if tinc could execute cabal with a bit more backjumps...

**Comment by phadej** [comment]
ping @sol, @soenkehahn, @mgsloan

Rebased, removed `manual` and `default` defaults, which is probably better as the defaults aren't obvious.

**Comment by sol** [comment]
A problem with my initial code is that it does not handle warnings in conditional blocks.

**Comment by phadej** [comment]
@sol, I see. I'll fix that.

**Comment by phadej** [comment]
@sol, It's fixed. The approach is a bit unsatisfactory as the framework highly assumes we parse flat data.

I could make largish refactor, introducing `StrictFromJSON a` which would produce `Parser (CaptureUnknownFields a)` directly.

**Comment by sol** [comment]
@phadej I think this still has issues.  E.g. it does not warn on `github` inside a top-level conditional block, but `github` is never allowed in a conditional block.

**Comment by sol** [comment]
I gave conditionals an other try #78.

**Comment by sol** [comment]
@phadej Let's sort out #78 first.  Once we have support for conditionals on `master` let's tackle support for flags.

**Pull request closed without merging**
