### PR TITLE
Support custom cabal-version field

### PR DESCRIPTION
**Pull request by mizunashi-mana**
related #213

### CODE REVIEW

**Comment by sol** [comment]
@mizunashi-mana thank you for taking the time to open this PR.

With the current state of the discussion I don't see the need for this change.  Generally, I know of two cases when you wan't to specify a Cabal version:

1. You have a custom `Setup.hs` that requires a certain version of the `Cabal` library.  In that case you can add something like
   ```yaml
   custom-setup:
     dependencies: Cabal == 2.*
   ```
   to `package.yaml`.
1. Your generated cabal file uses features that require a specific version of `Cabal` / `cabal-install`.  In this case it is the responsibility of `hpack` to add the appropriate `cabal-version` to the cabal file when generating it.  If that does not happen, e.g. as with #213, then thats at bug and we rather fix that bug in `hpack` than requiring users of `hpack` to figure out what `cabal-version` is needed and setting it manually.

Unless somebody can give a use case that does not fall in one of this categories, this is a `wontfix`.

**Comment by mizunashi-mana** [comment]
@sol I see.  Should I close this PR?

**Comment by quasicomputational** [comment]
FWIW I think it might be worth having an escape hatch here so that, if hpack is getting it wrong, you're not stuffed until you can get a PR merged here, then wait for stack to make a release that includes a hpack release with the fix. But, any use of such an escape hatch ought to be regarded as a work-around for a bug in hpack, I agree.

**Comment by sol** [comment]
I propose https://github.com/sol/hpack/issues/262 as a way to workaround issues like this.

**Comment by sol** [comment]
Closing.

**Pull request closed without merging**
